### ISSUE TITLE
Cannot upgrade to react-native v0.63.4

### ISSUE THREAD

**Issue by tijs** [mopinion/mopinion-sdk-react-native#27]
It seems we are blocked from updating to the latest bugfix release of react-native because of an outdated dependency installed by mopinion. Please resolve this asap as we will have to stop using mopinion if we cannot upgrade RN anymore because of it.

I get the following error in my packager after upgrading RN with the latest Mopinon version (1.4.0) installed.

```
error: ReferenceError: SHA-1 for file <redacted>/node_modules/react-native-material-buttons/node_modules/react-native/package.json (<redacted>/node_modules/react-native-material-buttons/node_modules/react-native/package.json) is not computed
    at DependencyGraph.getSha1 (<redacted>/node_modules/metro/src/node-haste/DependencyGraph.js:263:13)
    at <redacted>/node_modules/metro/src/DeltaBundler/Transformer.js:211:26
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/<redacted>/node_modules/metro/src/DeltaBundler/Transformer.js:46:24)
    at _next (<redacted>/node_modules/metro/src/DeltaBundler/Transformer.js:66:9)
    at<redacted>/node_modules/metro/src/DeltaBundler/Transformer.js:71:7
    at new Promise (<anonymous>)
    at <redacted>/node_modules/metro/src/DeltaBundler/Transformer.js:63:12
    at Transformer.transformFile (<redacted>/node_modules/metro/src/DeltaBundler/Transformer.js:236:7)
    at <redacted>/node_modules/metro/src/Bundler.js:87:34
```

**Comment by tijs** [comment]
FYI: v0.63.3 of react-native is the highest version i was able to upgrade too without getting this error

**Comment by tijs** [comment]
Tried again with 1.4.1 and now i can upgrade
